name: Uptime Worker
version: "1.0.0"
slug: uptimeworker
description: Self-hosted Uptime Worker monitoring server
url: https://github.com/esaueng/uptimeworker/tree/docker
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
webui: http://[HOST]:[PORT:3001]
watchdog: http://[HOST]:[PORT:3001]/api/entry-page
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Uptime Worker web interface
options: {}
schema: {}
stage: experimental
