services:
  uptimeworker:
    build:
      context: .
      dockerfile: Dockerfile
    image: uptimeworker:local
    container_name: uptimeworker
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      # <Host Port>:<Container Port>
      - "3001:3001"
